import{createGiftState}from"./gift-state.js";import{cameraModule,startCamera,stopCamera,isCameraRunning}from"./camera.js";import{recognitionModule,createDescriptor,saveReference,getReferences,clearReferences,getMaxReferences,getThreshold,startRecognitionLoop,stopRecognitionLoop}from"./recognition.js";import{xrAdapterModule}from"./xr-adapter.js";import{placementModule}from"./placement.js";import{experienceModule}from"./experience.js";import{rendererModule}from"./renderer.js";import{assetModule}from"./assets.js";import{getBasicCapabilities}from"./capabilities.js";import{getUI,setHomeStatus}from"./ui.js";
const VERSION="0.3.1",BASELINE="0.2.0",modules=[cameraModule,recognitionModule,xrAdapterModule,placementModule,experienceModule,rendererModule,assetModule];let ui,state,bound=false;
function refsUI(){const c=getReferences().length,t=`${c} / ${getMaxReferences()}`;ui.referenceCountHome.textContent=t;ui.referenceCountCamera.textContent=t;ui.btnCaptureReference.disabled=c>=getMaxReferences();ui.btnClearReferencesHome.disabled=c===0}
function stopRec(){stopRecognitionLoop();state.recognitionStatus="idle";ui.btnToggleRecognition.textContent="Start herkennen";ui.recognitionFeedback.textContent="";ui.similarityValue.textContent="—";ui.scanBox.classList.remove("match")}
function setMode(m){state.mode=m;const r=m==="register";ui.modeTitle.textContent=r?"Object registreren":"Object herkennen";ui.modeSubtitle.textContent=r?"Plaats het object in het kader":"Richt op het geregistreerde object";ui.registerControls.classList.toggle("hidden",!r);ui.recognizeControls.classList.toggle("hidden",r);stopRec()}
async function enter(m){try{if(m==="recognize"&&!getReferences().length){setHomeStatus(ui.homeStatus,"Registreer eerst minstens één aanzicht.","warn");return}setMode(m);ui.homeView.hidden=true;ui.cameraView.classList.add("active");ui.cameraView.setAttribute("aria-hidden","false");ui.cameraStatus.textContent="Camera starten…";await startCamera(ui.cameraPreview);state.cameraStatus="running";ui.cameraStateValue.textContent="actief";ui.cameraStatus.textContent="Camera actief"}catch(e){console.error(e);await leave();setHomeStatus(ui.homeStatus,e?.name==="NotAllowedError"?"Cameratoegang geweigerd.":`Camera kon niet starten: ${e.message}`,"error")}}
async function leave(){stopRec();await stopCamera(ui.cameraPreview);state.cameraStatus="stopped";ui.cameraStateValue.textContent="gestopt";ui.cameraView.classList.remove("active");ui.cameraView.setAttribute("aria-hidden","true");ui.homeView.hidden=false;state.mode="home"}
function capture(){try{const d=createDescriptor(ui.cameraPreview,ui.analysisCanvas),c=saveReference(d);refsUI();ui.recognitionFeedback.textContent=c<getMaxReferences()?`Aanzicht ${c} opgeslagen — draai het object`:"Registratie compleet"}catch(e){ui.recognitionFeedback.textContent=e.message}}
function toggle(){if(state.recognitionStatus==="running"){stopRec();return}try{state.recognitionStatus="running";ui.btnToggleRecognition.textContent="Stop herkennen";ui.recognitionFeedback.textContent="Zoeken…";startRecognitionLoop({video:ui.cameraPreview,canvas:ui.analysisCanvas,onResult:({similarity,matched,error})=>{if(error){ui.recognitionFeedback.textContent=`Fout: ${error.message}`;return}const p=Math.round(similarity*100);ui.similarityValue.textContent=`${p}%`;ui.recognitionFeedback.textContent=matched?"CADEAU HERKEND ✓":"Zoeken…";ui.scanBox.classList.toggle("match",matched)}})}catch(e){stopRec();ui.recognitionFeedback.textContent=e.message}}
function selftest(){try{const c=getBasicCapabilities();if(!modules.every(m=>m.ready))throw new Error("Niet alle modules gereed.");setHomeStatus(ui.homeStatus,`Basistest geslaagd. Secure context: ${c.secureContext?"ja":"nee"}. getUserMedia: ${c.getUserMediaPresent?"ja":"nee"}. LocalStorage: ${c.localStoragePresent?"ja":"nee"}.`,"ok")}catch(e){setHomeStatus(ui.homeStatus,`Basistest mislukt: ${e.message}`,"error")}}
function bind(){if(bound)return;ui.btnEnterRegister.addEventListener("click",()=>enter("register"));ui.btnEnterRecognize.addEventListener("click",()=>enter("recognize"));ui.btnBack.addEventListener("click",leave);ui.btnCaptureReference.addEventListener("click",capture);ui.btnToggleRecognition.addEventListener("click",toggle);ui.btnClearReferencesHome.addEventListener("click",()=>{stopRec();clearReferences();refsUI();setHomeStatus(ui.homeStatus,"Registratie gewist.","ok")});ui.btnSelfTest.addEventListener("click",selftest);document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.mode!=="home")leave()});window.addEventListener("pagehide",()=>{if(state?.mode!=="home")leave()});bound=true}
function init(){ui=getUI();state=createGiftState();ui.versionValue.textContent=VERSION;ui.baselineValue.textContent=BASELINE;ui.thresholdValue.textContent=`${Math.round(getThreshold()*100)}%`;bind();refsUI();setHomeStatus(ui.homeStatus,`Gift AR v${VERSION} is correct gestart.`,"ok")}
window.addEventListener("DOMContentLoaded",init,{once:true});