import{startCamera,stopCamera,cameraModule}from"./camera.js";import{load,add,remove,finish,limits,freeze,crop,registrationModule}from"./registration.js";import{$,uiModule}from"./ui.js";import{capabilities,capabilitiesModule}from"./capabilities.js";import{recognitionModule}from"./recognition.js";import{giftStateModule}from"./gift-state.js";import{xrAdapterModule}from"./xr-adapter.js";import{placementModule}from"./placement.js";import{experienceModule}from"./experience.js";import{rendererModule}from"./renderer.js";import{assetsModule}from"./assets.js";import{aiAssistanceModule}from"./ai-assistance.js";
const modules=[cameraModule,registrationModule,uiModule,capabilitiesModule,recognitionModule,giftStateModule,xrAdapterModule,placementModule,experienceModule,rendererModule,assetsModule,aiAssistanceModule];
const ids=["home","cam","status","start","galleryBtn","finish","test","gallery","video","freeze","back","title","selectLayer","box","shot","selectBtns","reset","preview","confirmBtns","crop","edit","save"],u={};ids.forEach(i=>u[i]=$(i));let mode="home",sel=null,drag=null,current=null;
function gallery(){let p=load();u.gallery.innerHTML="<h3>Aanzichten "+p.views.length+"/5</h3>";p.views.forEach(v=>{let d=document.createElement("div");d.className="thumb";let im=document.createElement("img");im.src=v.dataUrl;let t=document.createElement("p");t.textContent="Aanzicht "+v.order;let b=document.createElement("button");b.textContent="Verwijder";b.onclick=()=>{remove(v.id);gallery()};d.append(im,t,b);u.gallery.append(d)});u.finish.disabled=p.views.length<limits.min;u.start.disabled=p.views.length>=limits.max}
async function enter(){if(load().views.length>=5)return;mode="camera";u.home.hidden=true;u.cam.hidden=false;u.freeze.style.display="none";u.video.style.display="block";u.selectLayer.hidden=true;u.selectBtns.hidden=true;u.confirmBtns.hidden=true;u.shot.hidden=false;u.title.textContent="Neem een foto — aanzicht "+(load().views.length+1);await startCamera(u.video)}
async function leave(){await stopCamera(u.video);mode="home";u.cam.hidden=true;u.home.hidden=false;gallery()}
u.start.onclick=enter;u.galleryBtn.onclick=gallery;u.back.onclick=leave;u.shot.onclick=()=>{freeze(u.video,u.freeze);u.video.style.display="none";u.freeze.style.display="block";u.shot.hidden=true;u.selectLayer.hidden=false;u.selectBtns.hidden=false;u.title.textContent="Duid het cadeau aan";mode="select"};
function setBox(){let r=u.selectLayer.getBoundingClientRect();u.box.style.left=(sel.left-r.left)+"px";u.box.style.top=(sel.top-r.top)+"px";u.box.style.width=sel.width+"px";u.box.style.height=sel.height+"px";u.box.hidden=false}
u.selectLayer.onpointerdown=e=>{if(mode!=="select")return;drag={x:e.clientX,y:e.clientY};sel={left:e.clientX,top:e.clientY,width:0,height:0};u.selectLayer.setPointerCapture(e.pointerId)};
u.selectLayer.onpointermove=e=>{if(!drag)return;sel={left:Math.min(drag.x,e.clientX),top:Math.min(drag.y,e.clientY),width:Math.abs(e.clientX-drag.x),height:Math.abs(e.clientY-drag.y)};setBox()};
u.selectLayer.onpointerup=()=>{drag=null;if(sel&&(sel.width<40||sel.height<40)){sel=null;u.box.hidden=true}};
u.reset.onclick=()=>{sel=null;u.box.hidden=true};u.preview.onclick=()=>{if(!sel){u.title.textContent="Maak eerst een selectie";return}current=crop(u.freeze,u.box,u.crop);u.selectLayer.hidden=true;u.selectBtns.hidden=true;u.confirmBtns.hidden=false;u.title.textContent="Controleer aanzicht";mode="confirm"};
u.edit.onclick=()=>{u.confirmBtns.hidden=true;u.selectBtns.hidden=false;u.selectLayer.hidden=false;mode="select"};
u.save.onclick=async()=>{add(current);u.status.textContent="Aanzicht opgeslagen. Draai het cadeau voor het volgende aanzicht.";await leave()};
u.finish.onclick=()=>{try{let p=finish();u.status.textContent="Registratie afgerond met "+p.views.length+" aanzichten.";gallery()}catch(e){u.status.textContent=e.message}};
u.test.onclick=()=>{let c=capabilities();u.status.textContent=modules.every(m=>m.ready)&&c.camera&&c.storage?"Basistest geslaagd. Alle 12 modules geladen.":"Basistest niet geslaagd."};
document.addEventListener("visibilitychange",()=>{if(document.hidden&&mode!=="home")leave()});window.addEventListener("pagehide",()=>{if(mode!=="home")stopCamera(u.video)});gallery();