import{cameraModule,startCamera,stopCamera}from"./camera.js";import{registrationModule,loadProfile,addView,removeView,finishProfile,getLimits,freezeVisibleFrame,cropSelection}from"./registration.js";import{getUI,setStatus}from"./ui.js";import{getCapabilities}from"./capabilities.js";
const VERSION="0.5.1",BASELINE="0.2.0",modules=[cameraModule,registrationModule];let ui,mode="home",drag=null,selection=null,currentCrop=null,bound=false;
const profile=()=>loadProfile();
function renderGallery(){const p=profile();ui.galleryGrid.innerHTML="";p.views.forEach(v=>{const item=document.createElement("article");item.className="gallery-item";const img=document.createElement("img");img.src=v.dataUrl;img.alt=`Aanzicht ${v.order}`;const meta=document.createElement("div");meta.className="gallery-item-meta";meta.innerHTML=`<span>Aanzicht ${v.order}</span><span>${v.width}×${v.height}</span>`;const del=document.createElement("button");del.className="danger";del.textContent="Verwijderen";del.addEventListener("click",()=>{removeView(v.id);updateHome();setStatus(ui.homeStatus,"Aanzicht verwijderd.","ok")});item.append(img,meta,del);ui.galleryGrid.append(item)})}
function updateHome(){const p=profile(),l=getLimits(),c=p.views.length;ui.referenceCountHome.textContent=`${c} / ${l.max}`;ui.galleryCountValue.textContent=`${c} / ${l.max}`;ui.btnShowGallery.disabled=c===0;ui.btnFinishRegistration.disabled=c<l.min;ui.btnContinueRegistration.disabled=c>=l.max;ui.registrationStateValue.textContent=p.status==="completed"?"afgerond":c>=l.min?"klaar om af te ronden":c>0?`nog ${l.min-c} nodig`:"leeg";renderGallery()}
function showGallery(){updateHome();ui.galleryCard.classList.toggle("hidden")}
function resetCapture(){selection=null;drag=null;currentCrop=null;ui.cameraView.classList.remove("frozen");ui.selectionLayer.classList.add("hidden");ui.selectionBox.classList.add("hidden");ui.captureControls.classList.remove("hidden");ui.selectControls.classList.add("hidden");ui.confirmControls.classList.add("hidden");ui.afterSaveControls.classList.add("hidden");ui.cameraFeedback.textContent=""}
async function enter(){try{const p=profile(),l=getLimits();if(p.views.length>=l.max){setStatus(ui.homeStatus,"Maximum van 5 aanzichten bereikt.","warn");ui.galleryCard.classList.remove("hidden");return}mode="camera";resetCapture();ui.homeView.hidden=true;ui.cameraView.classList.add("active");ui.modeTitle.textContent="Neem een foto";ui.modeSubtitle.textContent=`Aanzicht ${p.views.length+1}`;ui.viewCounterTop.textContent=`${p.views.length} / ${l.max}`;await startCamera(ui.cameraPreview);ui.cameraStateValue.textContent="actief"}catch(e){console.error(e);await leave();setStatus(ui.homeStatus,`Camera kon niet starten: ${e.message}`,"error")}}
async function leave(){await stopCamera(ui.cameraPreview);mode="home";ui.cameraStateValue.textContent="gestopt";ui.cameraView.classList.remove("active","frozen");ui.homeView.hidden=false;updateHome()}
function take(){try{freezeVisibleFrame(ui.cameraPreview,ui.frozenCanvas);ui.cameraView.classList.add("frozen");mode="select";ui.captureControls.classList.add("hidden");ui.selectControls.classList.remove("hidden");ui.selectionLayer.classList.remove("hidden");ui.modeTitle.textContent="Duid je cadeau aan";ui.modeSubtitle.textContent="Selecteer alleen het cadeau";ui.cameraFeedback.textContent="Trek een rechthoek rond het cadeau."}catch(e){ui.cameraFeedback.textContent=e.message}}
function resetSel(){selection=null;ui.selectionBox.classList.add("hidden");ui.cameraFeedback.textContent="Maak een nieuwe selectie."}
const rect=(x1,y1,x2,y2)=>({left:Math.min(x1,x2),top:Math.min(y1,y2),width:Math.abs(x2-x1),height:Math.abs(y2-y1)});
function apply(){if(!selection)return;const l=ui.selectionLayer.getBoundingClientRect();ui.selectionBox.style.left=`${selection.left-l.left}px`;ui.selectionBox.style.top=`${selection.top-l.top}px`;ui.selectionBox.style.width=`${selection.width}px`;ui.selectionBox.style.height=`${selection.height}px`;ui.selectionBox.classList.remove("hidden")}
function down(e){if(mode!=="select")return;const h=e.target?.dataset?.handle;if(h&&selection)drag={type:"resize",handle:h,initial:{...selection}};else{drag={type:"new",startX:e.clientX,startY:e.clientY};selection={left:e.clientX,top:e.clientY,width:0,height:0}}ui.selectionLayer.setPointerCapture?.(e.pointerId);e.preventDefault()}
function move(e){if(!drag||mode!=="select")return;if(drag.type==="new")selection=rect(drag.startX,drag.startY,e.clientX,e.clientY);else{const i=drag.initial;let l=i.left,t=i.top,r=i.left+i.width,b=i.top+i.height;if(drag.handle.includes("n"))t=e.clientY;if(drag.handle.includes("s"))b=e.clientY;if(drag.handle.includes("w"))l=e.clientX;if(drag.handle.includes("e"))r=e.clientX;selection=rect(l,t,r,b)}const layer=ui.selectionLayer.getBoundingClientRect();selection.left=Math.max(layer.left,Math.min(selection.left,layer.right-20));selection.top=Math.max(layer.top,Math.min(selection.top,layer.bottom-20));selection.width=Math.min(selection.width,layer.right-selection.left);selection.height=Math.min(selection.height,layer.bottom-selection.top);apply();e.preventDefault()}
function up(e){if(!drag)return;drag=null;if(selection&&selection.width>=40&&selection.height>=40)ui.cameraFeedback.textContent="Selectie gemaakt.";else resetSel();try{ui.selectionLayer.releasePointerCapture?.(e.pointerId)}catch{}}
function preview(){try{if(!selection)throw new Error("Duid eerst het cadeau aan.");currentCrop=cropSelection(ui.frozenCanvas,ui.selectionBox.getBoundingClientRect(),ui.frozenCanvas.getBoundingClientRect(),ui.cropPreviewCanvas);mode="confirm";ui.selectionLayer.classList.add("hidden");ui.selectControls.classList.add("hidden");ui.confirmControls.classList.remove("hidden");ui.modeTitle.textContent="Controleer aanzicht";ui.modeSubtitle.textContent="Dit wordt opgeslagen"}catch(e){ui.cameraFeedback.textContent=e.message}}
function edit(){mode="select";ui.selectionLayer.classList.remove("hidden");ui.selectControls.classList.remove("hidden");ui.confirmControls.classList.add("hidden")}
function confirm(){try{const p=addView(currentCrop),l=getLimits();mode="saved";ui.confirmControls.classList.add("hidden");ui.afterSaveControls.classList.remove("hidden");ui.viewCounterTop.textContent=`${p.views.length} / ${l.max}`;ui.modeTitle.textContent="Aanzicht opgeslagen";if(p.views.length<l.min)ui.afterSaveMessage.textContent="Draai het cadeau voor een duidelijk ander aanzicht.";else if(p.views.length<l.max)ui.afterSaveMessage.textContent="Minimum bereikt. Je kunt afronden of extra aanzichten toevoegen.";else{ui.afterSaveMessage.textContent="Maximum van 5 bereikt.";ui.btnNextView.disabled=true}}catch(e){ui.cameraFeedback.textContent=e.message}}
async function next(){await leave();await enter()}
async function gallery(){await leave();ui.galleryCard.classList.remove("hidden")}
function finish(){try{const p=finishProfile();updateHome();ui.galleryCard.classList.remove("hidden");setStatus(ui.homeStatus,`Registratie afgerond met ${p.views.length} aanzichten.`,"ok")}catch(e){setStatus(ui.homeStatus,e.message,"warn")}}
function selftest(){try{const c=getCapabilities();if(!modules.every(m=>m.ready))throw new Error("Niet alle modules gereed.");setStatus(ui.homeStatus,`Basistest geslaagd. Secure context: ${c.secureContext?"ja":"nee"}. Camera API: ${c.camera?"ja":"nee"}. LocalStorage: ${c.localStorage?"ja":"nee"}.`,"ok")}catch(e){setStatus(ui.homeStatus,`Basistest mislukt: ${e.message}`,"error")}}
function bind(){if(bound)return;ui.btnStartRegistration.addEventListener("click",enter);ui.btnContinueRegistration.addEventListener("click",enter);ui.btnShowGallery.addEventListener("click",showGallery);ui.btnFinishRegistration.addEventListener("click",finish);ui.btnSelfTest.addEventListener("click",selftest);ui.btnBack.addEventListener("click",leave);ui.btnTakePhoto.addEventListener("click",take);ui.btnResetSelection.addEventListener("click",resetSel);ui.btnPreviewSelection.addEventListener("click",preview);ui.btnEditSelection.addEventListener("click",edit);ui.btnConfirmSelection.addEventListener("click",confirm);ui.btnNextView.addEventListener("click",next);ui.btnBackToGallery.addEventListener("click",gallery);ui.selectionLayer.addEventListener("pointerdown",down);ui.selectionLayer.addEventListener("pointermove",move);ui.selectionLayer.addEventListener("pointerup",up);ui.selectionLayer.addEventListener("pointercancel",up);document.addEventListener("visibilitychange",()=>{if(document.hidden&&mode!=="home")leave()});window.addEventListener("pagehide",()=>{if(mode!=="home")leave()});bound=true}
function init(){ui=getUI();ui.versionValue.textContent=VERSION;ui.baselineValue.textContent=BASELINE;bind();updateHome();setStatus(ui.homeStatus,`Gift AR v${VERSION} is correct gestart.`,"ok")}
window.addEventListener("DOMContentLoaded",init,{once:true});